kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}-node-service
spec:
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}
  ports:
  - name: node-port
    port: {{ .Values.env.nodePort }}
  - name: client-port
    port: {{ .Values.env.clientPort }}